[build]
  publish = "."
  command = "echo 'No build command needed'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/secret_sauce/functions/:splat"
  status = 200

[functions]
  directory = "secret_sauce/functions"
